import { Factory, QualityKPIs, ParetoErrorItem, IncidentItem } from "./types";

export const FACTORIES: Factory[] = [
  {
    id: "all",
    code: "ALL",
    name: "Toàn chuỗi SKECHERS",
    status: "live",
    enabled: true,
  },
  {
    id: "kg1",
    code: "KG1",
    name: "Nhà máy Kiên Giang 1",
    location: "Kiên Giang, Việt Nam",
    status: "live",
    portalUrl: "https://hethongphanhoiclsk.tbsgroup2026.workers.dev/portal",
    enabled: true,
    workshops: [
      { name: "Xưởng A", linesCount: 8 },
      { name: "Xưởng B", linesCount: 8 },
      { name: "Xưởng C", linesCount: 8 },
    ],
    totalLines: 24,
    oee: 98.2,
    openIncidents: 12,
    mttrMinutes: 38,
  },
  {
    id: "kg2",
    code: "KG2",
    name: "Nhà máy Kiên Giang 2",
    location: "Kiên Giang, Việt Nam",
    status: "planned",
    enabled: false,
    totalLines: 16,
    oee: 95.0,
    openIncidents: 0,
    mttrMinutes: 45,
  },
];

export const KG1_KPIS: QualityKPIs = {
  unprocessed: 12,
  processing: 8,
  trialRun: 3,
  completed: 126,
  emergencySOS: 1,
};

export const KG1_PARETO_ERRORS: ParetoErrorItem[] = [
  { id: "1", name: "Lỗi đường may", percentage: 32, count: 48, color: "#ef4444" },
  { id: "2", name: "Lỗi dán đế", percentage: 24, count: 36, color: "#f97316" },
  { id: "3", name: "Lỗi vật liệu", percentage: 18, count: 27, color: "#eab308" },
  { id: "4", name: "Lỗi kích thước", percentage: 15, count: 22, color: "#3b82f6" },
  { id: "5", name: "Lỗi khác", percentage: 11, count: 17, color: "#64748b" },
];

export const KG1_INCIDENTS: IncidentItem[] = [
  {
    id: "inc-1",
    code: "#KG1-00231",
    workshop: "Xưởng A",
    line: "Chuyền 03",
    team: "Tổ 02",
    errorType: "Lỗi máy ép đế thủy lực không đủ áp suất",
    severity: "high",
    status: "unprocessed",
    slaRemaining: "08:42",
    slaPercent: 58,
    createdAt: "10 phút trước",
    reporter: "QA001 - Nguyễn Văn Hùng",
  },
  {
    id: "inc-2",
    code: "#KG1-00230",
    workshop: "Xưởng B",
    line: "Chuyền 07",
    team: "Tổ 01",
    errorType: "Lỗi đường may lệch viền Upper Skechers D'Lites",
    severity: "medium",
    status: "processing",
    mttrMinutes: 32,
    createdAt: "25 phút trước",
    reporter: "LL001 - Trần Thị Mai",
  },
  {
    id: "inc-3",
    code: "#KG1-00229",
    workshop: "Xưởng A",
    line: "Chuyền 01",
    team: "Tổ 04",
    errorType: "Keo dán đế Outsole bị vón cục nhiệt độ thấp",
    severity: "critical",
    status: "processing",
    mttrMinutes: 18,
    createdAt: "40 phút trước",
    reporter: "CN001 - Lê Hoàng Nam",
  },
  {
    id: "inc-4",
    code: "#KG1-00228",
    workshop: "Xưởng C",
    line: "Chuyền 12",
    team: "Tổ 03",
    errorType: "Kiểm định thử nghiệm độ uốn gập sau sửa máy may",
    severity: "low",
    status: "trial",
    slaRemaining: "Theo dõi 12h",
    slaPercent: 80,
    createdAt: "2 giờ trước",
    reporter: "QA002 - Phạm Minh Tuấn",
  },
  {
    id: "inc-5",
    code: "#KG1-00225",
    workshop: "Xưởng B",
    line: "Chuyền 05",
    team: "Tổ 02",
    errorType: "Xử lý lệch logo Skechers in nhiệt phần gót giày",
    severity: "low",
    status: "completed",
    mttrMinutes: 24,
    createdAt: "Hôm nay 08:30",
    reporter: "BT001 - Đặng Quốc Việt",
  },
];
